# Generated by Django 3.0.8 on 2020-07-16 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0006_auto_20200715_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Campaign')),
                ('memer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='memes/')),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('parent_meme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memerconnect', to='memers.Meme')),
            ],
            options={
                'verbose_name_plural': 'Meme Images',
            },
        ),
    ]
