# Generated by Django 3.0.8 on 2020-07-17 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memers', '0001_initial'),
        ('users', '0003_auto_20200710_1809'),
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignexecutionunit',
            name='memes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memers.MemeImages'),
        ),
        migrations.CreateModel(
            name='SocialMediaAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('y', 'youtube'), ('i', 'instagram'), ('f', 'facebook'), ('t', 'twitter')], max_length=20)),
                ('permissions_granted', models.BooleanField(default=False)),
                ('cpi', models.FloatField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Profile')),
            ],
        ),
    ]
