# Generated by Django 3.0.8 on 2020-07-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memers', '0001_initial'),
        ('influencers', '0002_auto_20200717_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignexecutionunit',
            name='memes',
        ),
        migrations.AddField(
            model_name='campaignexecutionunit',
            name='memes',
            field=models.ManyToManyField(blank=True, null=True, to='memers.MemeImages'),
        ),
        migrations.AlterField(
            model_name='socialmediaasset',
            name='platform',
            field=models.CharField(choices=[('i', 'instagram'), ('y', 'youtube'), ('t', 'twitter'), ('f', 'facebook')], max_length=20),
        ),
    ]
