# Generated by Django 3.0.8 on 2020-07-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memers', '0001_initial'),
        ('influencers', '0003_auto_20200717_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignexecutionunit',
            name='memes',
            field=models.ManyToManyField(blank=True, to='memers.MemeImages'),
        ),
        migrations.AlterField(
            model_name='socialmediaasset',
            name='platform',
            field=models.CharField(choices=[('t', 'twitter'), ('i', 'instagram'), ('f', 'facebook'), ('y', 'youtube')], max_length=20),
        ),
    ]
