# Generated by Django 3.0.8 on 2020-07-17 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('influencers', '0009_auto_20200717_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignexecutionunit',
            name='social_media_platform',
            field=models.CharField(choices=[('f', 'facebook'), ('y', 'youtube'), ('t', 'twitter'), ('i', 'instagram')], max_length=50),
        ),
        migrations.AlterField(
            model_name='socialmediaasset',
            name='platform',
            field=models.CharField(choices=[('f', 'facebook'), ('y', 'youtube'), ('t', 'twitter'), ('i', 'instagram')], max_length=20),
        ),
        migrations.AlterField(
            model_name='socialmediaasset',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
