# Generated by Django 3.0.8 on 2020-07-15 07:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1.7, 'Facebook Groups'), (1.3, 'Facebook Posts'), (1.9, 'Instagram Posts'), (1.2, 'Twitter Posts'), (1.1, 'Twitter Trends'), (0.8, 'YouTube Features')], max_length=23, null=True),
        ),
    ]
