# Generated by Django 3.0.8 on 2020-07-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20200715_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='number_of_memes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
