# Generated by Django 3.0.8 on 2020-07-10 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignExecutionUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_platform', models.CharField(choices=[(1.7, 'Facebook Groups'), (1.3, 'Facebook Posts'), (1.9, 'Instagram Posts'), (1.2, 'Twitter Posts'), (1.1, 'Twitter Trends'), (0.8, 'YouTube Features')], max_length=50)),
                ('number_of_posts', models.IntegerField()),
                ('assigned_to_influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campaign_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Campaign')),
            ],
        ),
    ]
